/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bbtest;

import bbqa.Library;

public class LibraryTest {
    @org.testng.annotations.Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        
    }
}
